# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Config for handlers

    # CommandHandler
    App\CoffeeMachine\Application\CommandHandler\:
        resource: '../src/CoffeeMachine/Application/CommandHandler/'
        tags: [ 'messenger.message_handler' ]
        autowire: true
        autoconfigure: true

    # QueryHandler
    App\CoffeeMachine\Application\QueryHandler\:
        resource: '../src/CoffeeMachine/Application/QueryHandler/'
        tags: [ 'messenger.message_handler' ]
        autowire: true
        autoconfigure: true

    # Repositories
    App\CoffeeMachine\Domain\Repository\CoffeeMachineRepositoryInterface:
        class: App\CoffeeMachine\Infrastructure\Repository\CoffeeMachineRepository

    App\CoffeeMachine\Domain\Repository\CoffeeOrderRepositoryInterface:
        class: App\CoffeeMachine\Infrastructure\Repository\CoffeeOrderRepository

    # Resolver
    App\CoffeeMachine\Infrastructure\Resolver\RequestDTOResolver:
        tags: [ 'controller.argument_value_resolver' ]
