doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            machine_status: App\CoffeeMachine\Infrastructure\Doctrine\Type\MachineStatusType
            coffee_type: App\CoffeeMachine\Infrastructure\Doctrine\Type\CoffeeTypeType
            coffee_intensity: App\CoffeeMachine\Infrastructure\Doctrine\Type\CoffeeIntensityType
            sugar_level: App\CoffeeMachine\Infrastructure\Doctrine\Type\SugarLevelType
            order_status: App\CoffeeMachine\Infrastructure\Doctrine\Type\OrderStatusType

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            CoffeeMachine:
                type: xml
                dir: '%kernel.project_dir%/src/CoffeeMachine/Infrastructure/DoctrineMapping'
                prefix: 'App\CoffeeMachine\Domain\Entity'
                is_bundle: false

when@test:
    doctrine:
        dbal:
            dbname: 'coffee_machine_test'
            # "TEST_TOKEN"
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
