framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

            sync: 'sync://'

        default_bus: command.bus #messenger.bus.default

        buses:
            command.bus: ~
            query.bus: ~
            #messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Query
            'App\CoffeeMachine\Application\Query\*': sync

            # Commands
            'App\CoffeeMachine\Application\Command\CreateOrderCommand': sync
            'App\CoffeeMachine\Application\Command\StartMachineCommand': sync
            'App\CoffeeMachine\Application\Command\StopMachineCommand': sync
            'App\CoffeeMachine\Application\Command\CancelOrderCommand': sync

            # Messages
            'App\CoffeeMachine\Application\Message\StartOrderMessage': async

